apiVersion: rhpam.kiegroup.org/v1
kind: KogitoBuild
metadata:
  name: qlb-loan-preapproval-dmn
spec:
  runtime: quarkus
  type: Binary

---
apiVersion: rhpam.kiegroup.org/v1
kind: KogitoRuntime
metadata:
  name: qlb-loan-preapproval-dmn
spec:
  runtime: quarkus
  replicas: 1
